artifact_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0
creation_time: 1758013492439
experiment_id: '0'
last_update_time: 1758013492439
lifecycle_stage: active
name: Default
