aliases: []
creation_timestamp: 1759223099639
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1759223099639
metrics: null
model_id: m-0345d577740b45e188439d58ff4439f8
name: Best Model
params: null
run_id: 90b47cd916994256b65ce3ba2ecd1e84
run_link: null
source: models:/m-0345d577740b45e188439d58ff4439f8
status: READY
status_message: null
storage_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-0345d577740b45e188439d58ff4439f8/artifacts
user_id: null
version: 4
