artifact_uri: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/5440e4603414499b9887ca4c82a50107/artifacts
end_time: 1758872668886
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5440e4603414499b9887ca4c82a50107
run_name: painted-fly-961
source_name: ''
source_type: 4
source_version: ''
start_time: 1758872656973
status: 4
tags: []
user_id: akshayavardhini2004
