artifact_uri: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/1eebb3475bb34d0e954658fdce60d84d/artifacts
end_time: 1758013502408
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1eebb3475bb34d0e954658fdce60d84d
run_name: carefree-newt-136
source_name: ''
source_type: 4
source_version: ''
start_time: 1758013492645
status: 4
tags: []
user_id: akshayavardhini2004
