artifact_uri: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/ce84196b524b4cdb97fe6130155c3b45/artifacts
end_time: 1759217972611
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ce84196b524b4cdb97fe6130155c3b45
run_name: inquisitive-snake-40
source_name: ''
source_type: 4
source_version: ''
start_time: 1759217959363
status: 4
tags: []
user_id: akshayavardhini2004
