artifact_uri: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/b1e13a32371f42b0b65e5afa88f262f9/artifacts
end_time: 1759223865332
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b1e13a32371f42b0b65e5afa88f262f9
run_name: flawless-shrew-938
source_name: ''
source_type: 4
source_version: ''
start_time: 1759223856311
status: 3
tags: []
user_id: akshayavardhini2004
