artifact_uri: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/90b47cd916994256b65ce3ba2ecd1e84/artifacts
end_time: 1759223099688
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 90b47cd916994256b65ce3ba2ecd1e84
run_name: melodic-pug-44
source_name: ''
source_type: 4
source_version: ''
start_time: 1759223084216
status: 4
tags: []
user_id: akshayavardhini2004
