aliases: []
creation_timestamp: 1758013502366
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1758013502366
metrics: null
model_id: m-5e68eba24b444bbfa7ff18d315b92fc2
name: Best Model
params: null
run_id: 1eebb3475bb34d0e954658fdce60d84d
run_link: null
source: models:/m-5e68eba24b444bbfa7ff18d315b92fc2
status: READY
status_message: null
storage_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-5e68eba24b444bbfa7ff18d315b92fc2/artifacts
user_id: null
version: 1
