artifact_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-6f51bf93a05748008b77bc4f92e779b9/artifacts
creation_timestamp: 1759223862328
experiment_id: '0'
last_updated_timestamp: 1759223865210
model_id: m-6f51bf93a05748008b77bc4f92e779b9
model_type: null
name: model
source_run_id: b1e13a32371f42b0b65e5afa88f262f9
status: 2
status_message: null
