aliases: []
creation_timestamp: 1759217972564
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1759217972564
metrics: null
model_id: m-3ca76b1657b94104814dc0d799cd5394
name: Best Model
params: null
run_id: ce84196b524b4cdb97fe6130155c3b45
run_link: null
source: models:/m-3ca76b1657b94104814dc0d799cd5394
status: READY
status_message: null
storage_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-3ca76b1657b94104814dc0d799cd5394/artifacts
user_id: null
version: 3
