artifact_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-5e68eba24b444bbfa7ff18d315b92fc2/artifacts
creation_timestamp: 1758013498186
experiment_id: '0'
last_updated_timestamp: 1758013502338
model_id: m-5e68eba24b444bbfa7ff18d315b92fc2
model_type: null
name: model
source_run_id: 1eebb3475bb34d0e954658fdce60d84d
status: 2
status_message: null
