aliases: []
creation_timestamp: 1758872668836
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1758872668836
metrics: null
model_id: m-3079ca4f2a17451684686fd86cd6fdd0
name: Best Model
params: null
run_id: 5440e4603414499b9887ca4c82a50107
run_link: null
source: models:/m-3079ca4f2a17451684686fd86cd6fdd0
status: READY
status_message: null
storage_location: file:///C:/Users/aksha/OneDrive/Desktop/MLPIPELINE/ine.mlflow/0/models/m-3079ca4f2a17451684686fd86cd6fdd0/artifacts
user_id: null
version: 2
